const winnerTitle = [
    {
        country: "จีน",
        gold: "94",
        silver: "76",
        copper: "50",
        total: "220",
    },
    {
        country: "สหราชอาณาจักร",
        gold: "49",
        silver: "44",
        copper: "31",
        total: "124",
    },
    {
        country: "สหรัฐอเมริกา",
        gold: "36",
        silver: "42",
        copper: "27",
        total: "105",
    },
    {
        country: "เนเธอร์แลนด์",
        gold: "27",
        silver: "17",
        copper: "12",
        total: "56",
    },
    {
        country: "อิตาลี",
        gold: "25",
        silver: "26",
        copper: "38",
        total: "89",
    },
    {
        country: "บราซิล",
        gold: "24",
        silver: "15",
        copper: "32",
        total: "71",
    },
    {
        country: "ฝรั่งเศส",
        gold: "22",
        silver: "28",
        copper: "32",
        total: "82",
    },
    {
        country: "ยูเครน",
        gold: "19",
        silver: "28",
        copper: "28",
        total: "75",
    },
    {
        country: "ออสเตรเลีย",
        gold: "18",
        silver: "17",
        copper: "28",
        total: "63",
    },
    {
        country: "ญี่ปุ่น",
        gold: "14",
        silver: "10",
        copper: "17",
        total: "41",
    },
    {
        country: "ไทย",
        gold: "6",
        silver: "11",
        copper: "13",
        total: "30",
    },
];

export default winnerTitle;